### ISSUE TITLE
Missing svg file referenced in vertical-nav.css

### ISSUE THREAD

**Issue by app-generator** [creativetimofficial/ct-material-kit-pro#169]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
vertical-nav.css , Line 36 refers and locate successfully cd-arrow-bottom.svg

# Current Behavior

vertical-nav.css , refers unexisting file:
```css
.cd-scroll-down {
  position: absolute;
....
  background: url("../img/cd-arrow-bottom.svg") no-repeat center center;
}

```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open `assets/demo/vertical-nav.css`

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Any
* Operating System: Any
* Browser and Version: Any
