### ISSUE TITLE
Floating label doesn't float if initialized with a value

### ISSUE THREAD

**Issue by gamut** [creativetimofficial/ct-material-kit-pro#6]
When the floating label on an input is used as per your example, and the control is initialized with a value, then the label should automatically float above it.  Right now it overlaps the text until you click inside it.

**Comment by alexandru-paduraru** [comment]
@gamut thank you for using our product. Please remove the `.is-empty` class from the `.form-group` div. Then please add this code at the end of material-kit.css.

```css
.form-group.label-static label.control-label, .form-group.label-floating.is-focused label.control-label, .form-group.label-floating:not(.is-empty) label.control-label {
    top: -28px;
    left: 0;
    font-size: 11px;
    line-height: 1.07143;
}
```

This will overwrite some properties. Don't worry about writing over our CSS, we are preparing a release for v1.1.0 which is fixing that issue. All that you will have to do is to replace the CSS and JS. We will let you know when the update is available.

Best,
Alex
