### ISSUE TITLE
.show causing issues on dropdown afters in modals

### ISSUE THREAD

**Issue by KatherineGraham** [creativetimofficial/ct-material-kit-pro#88]
![screen shot 2018-04-11 at 4 13 10 pm](https://user-images.githubusercontent.com/38301720/38647885-62097266-3da3-11e8-92cc-ca41ad6f55bd.png)

Hello I am using the material kit ui to create a modal in react which contains dropdowns

Because when a modal shows .show is used all the dropdowns I have within my modal are effected by .show and their after carrots are flipped as if the dropdown content is shown.

I can't figure out what in css I can do to rectify this, I need the toggling after to be working properly.

This is the css that causes the rotation. It should be set the opposite direction if not open. I really believe this is due to .show being used for the modal as well.

.show .dropdown-toggle:after {
    -webkit-transform: rotate(180deg);
    -moz-transform: rotate(180deg);
    -o-transform: rotate(180deg);
    -ms-transform: rotate(180deg);
    transform: rotate(180deg);
}

**Comment by KatherineGraham** [comment]
It's a pretty straight forward problem and I explained it above. Anyone putting material kit dropdowns into the material kit modal should be able to re-create the issue. Both the dropdowns and modal use .show to effect their changes.

**Comment by dragosct10** [comment]
Hi! Please try to do this in you scss: 

```css
.show:not(.modal) .dropdown-toggle:after {
-webkit-transform: rotate(180deg);
-moz-transform: rotate(180deg);
-o-transform: rotate(180deg);
-ms-transform: rotate(180deg);
transform: rotate(180deg);
}
```

Regards, 
Dragos
